nome = input("Come ti chiami? ")
cognome = input("Quale e' il tuo cognome? ")
eta = input("Quanti anni hai? ")
citta = input("Dove abiti? ")
corso_di_studi = input("Che cosa studi ")

print()
print("-------------------------")
print("CARTA D'IDENTITÀ")
print("-------------------------")
print(f"Nome: {nome}")
print(f"Cognome: {cognome}")
print(f"Età: {eta}")
print(f"Città: {citta}")
print(f"Corso di studi: {corso_di_studi}")
print("-------------------------")
